apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    kind: PersistentVolumeClaim
    name: host-pvc
    namespace: demo
  backends:
  - name: gcs-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: pvc-backup
    sessionHistoryLimit: 
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: pvc
      backend: gcs-storage
      directory: /pvc
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: demo
      deletionPolicy: WipeOut 
    addon:
      name: pvc-addon
      tasks:
      - name: pvc-backup
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0
    retryConfig:
      maxRetry: 2
      delay: 1m