apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-host-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem