kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c","echo 'hello from pod 1.' > /source/data/hello.txt && sleep 3000"]
    volumeMounts:
    - name: my-volume
      mountPath: /source/data
      subPath: pod-1/data
  volumes:
  - name: my-volume
    hostPath:
      path: /test