apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup-dep
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: Deployment
    name: sample-deploy
    namespace: demo
  backends:
  - name: gcs-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: workload-backup
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: demo-storage-1
      backend: gcs-storage
      directory: /data/sample-deploy
      encryptionSecret:
        name: encry-secret
        namespace: demo
    addon:
      name: workload-addon
      tasks:
      - name: backup-workload
        targetVolumes:
          volumeMounts:
          - name: cache-volume
            mountPath: /cache/data
        params:
          paths: /cache/data
    retryConfig:
      maxRetry: 2
      delay: 1m