apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup-sts
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    name: sample-sts
    namespace: demo
  backends:
  - name: gcs-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: two-minute-backup-cycle
    scheduler: # CronJob specification
      schedule: "*/5 * * * *"
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: demo-storage-1
      backend: gcs-storage
      directory: /data/sample-sts
      encryptionSecret:
        name: encry-secret
        namespace: demo
    addon:
      name: workload-addon
      tasks:
      - name: backup-workload
        targetVolumes:
          volumeMounts:
          - name: source-data
            mountPath: /source/data
        params:
          paths: /source/data
          exclude: /source/data/lost+found
      jobTemplate:
        spec:
          serviceAccountName: bucket-user
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
    retryConfig:
      maxRetry: 2
      delay: 1m
