apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Postgres
    namespace: demo
    name: sample-postgres
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: manifest-backup
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: pg-storage
      backend: s3-storage
      directory: /manifest/postgres-manifest
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: demo
    addon:
      name: kubedb-manifest-addon
      tasks:
      - name: backup-manifest
    failurePolicy: Retry # Default to "Fail"
    retryConfig:
      maxRetry: 2
      delay: 1m
