apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restore
  namespace: demo
spec:
  manifestOptions:
    restoreNamespace: demo2
    postgres:
      db: true
      dbName: new-db
      authSecret: true
      authSecretName: new-db-ss
      configSecret: true
  dataSource:
    snapshot: latest
    repository: pg-storage
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: kubedb-manifest-addon
    tasks:
    - name: restore-manifest
