apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup-dep
  namespace: default
spec:
  target:
    apiGroup: apps
    kind: Deployment
    name: busy-dep
    namespace: default
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: default
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: workload-backup
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: demo-storage-1
      backend: s3-storage
      directory: /dep/deployment
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: default
    addon:
      name: workload-addon
      tasks:
      - name: backup-workload
        params:
          paths: 
            value: /cache
    retryConfig:
      maxRetry: 2
      delay: 1m
