apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mgo-quickstart
  namespace: default
  annotations:
    blueprint.kubestash.com/sessions: manifest-backup
    blueprint.kubestash.com/name: my-bb
    blueprint.kubestash.com/namespace: default
spec:
  version: "4.4.6"
  replicaSet:
    name: "rs1"
  replicas: 2
  storageType: Durable
  storage:
    # storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete

