apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-backup
spec:
  image: ishtiaq99/workload:0c1dc11_linux_amd64
  args:
  - backup
  - --scratch-dir=/tmp
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --paths=${paths:=}
  - --exclude=${exclude:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-restore
spec:
  image: ishtiaq99/workload:0c1dc11_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --exclude=${exclude:=}
  - --include=${include:=}

---

apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: gcs-storage
  namespace: demo
spec:
  storage:
    provider: gcs
    gcs:
      bucket: kubestash
      prefix: demo
      secret: gcs-secret 
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true # Use this BackupStorage as the default
  deletionPolicy: WipeOut # One of: WipeOut, Delete

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: workload-addon
  namespace: demo
spec:
  backupTasks:
  - name: backup-workload
    function: workload-backup
    driver: Restic #Restic, WalG
    executor: Job #Job, Sidecar, EphemeralContainer, MultiLevelJob
    singleton: false
    parameters:
    - name: paths
      usage: Specifies list of file paths to backup.
      required: true
    - name: exclude
      usage: Specifies a list of patterns for the files that should be ignored during backup.
      required: false
  restoreTasks:
  - name: restore-workload
    function: workload-restore
    driver: Restic
    executor: Job
    singleton: false
    parameters:
    - name: exclude
      usage: Specifies a list of patterns for the files that should be ignored during restore.
      required: false
    - name: include
      usage: Specifies a list of patterns for the files that should be restored
      required: false

---

apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: demo-retention
  namespace: demo
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 5
  failedSnapshots:
    last: 2
  usagePolicy:
    allowedNamespaces:
      from: All