apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 0
  selector:
    app: rsts-demo
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: restore-sts
  namespace: demo
  labels:
    app: rsts-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsts-demo
  serviceName: headless
  template:
    metadata:
      labels:
        app: rsts-demo
    spec:
      containers:
      - name: busybox
        image: busybox
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        command: ["/bin/sh", "-c","echo test > /source/data/data.txt && sleep 3000"]
        volumeMounts:
        - name: source-data
          mountPath: "/source/data"
        imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: source-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 256Mi
