apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup-sts
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    name: sample-sts
    namespace: demo
  backends:
  - name: gcs-backend
    storageRef: 
      name: gcs-storage
      namespace: demo
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: demo-session
    scheduler:
      schedule: "*/2 * * * *"
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: gcs-demo-repo
      backend: gcs-backend
      directory: /demo/data
      encryptionSecret:
        name: encry-secret
        namespace: demo
    addon:
      name: workload-addon
      tasks:
      - name: LogicalBackup
        targetVolumes:
          volumeMounts:
          - name: source-data
            mountPath: /source/data
        params:
          paths: /source/data
          exclude: /source/data/lost+found
    retryConfig:
      maxRetry: 2
      delay: 1m
  - name: demo-session-1
    scheduler:
      schedule: "*/5 * * * *"
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: gcs-demo-repo-1
      backend: gcs-backend
      directory: /demo/sts
      encryptionSecret:
        name: encry-secret
        namespace: demo
    addon:
      name: workload-addon
      tasks:
      - name: LogicalBackup
        targetVolumes:
          volumeMounts:
          - name: source-data
            mountPath: /source/data
        params:
          paths: /source/data
          exclude: /source/data/lost+found
    retryConfig:
      maxRetry: 2
      delay: 1m
