apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup
  namespace: default
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    name: web
    namespace: default
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: default
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: workload-backup
    sessionHistoryLimit: 50
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: demo-storage-0
      backend: s3-storage
      directory: /dep/sts
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: default
    addon:
      name: workload-addon
      tasks:
      - name: backup-workload
        targetVolumes:
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
        params:
          paths:
            value: /usr/share/nginx/html
          exclude: 
            value: /usr/share/nginx/html/tmp1
    retryConfig:
      maxRetry: 2
      delay: 1m