apiVersion: core.kubestash.com/v1alpha1
kind: BackupBlueprint
metadata:
  name: sts-blueprint
  namespace: default
spec:
  usagePolicy:
    allowedNamespaces: 
      from: All
  backupConfigurationTemplate:
    deletionPolicy: OnDelete
    backends:
    - name: s3-storage
      storageRef:
        apiGroup: storage.kubestash.com
        namespace: default
        kind: BackupStorage
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: default
    sessions:
    - name: workload-backup
      sessionHistoryLimit: 50
      scheduler: # CronJob specification
        schedule: "*/2 * * * *"
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 1
      repositories: # volume & volumeMount strategy.
      - name: demo-storage-0
        backend: s3-storage
        directory: sts/${namespace}/${targetName}
        encryptionSecret:
          name: encry-secret # some addon may not support encryption
          namespace: default
      addon:
        name: workload-addon
        tasks:
        - name: backup-workload
          targetVolumes:
            volumeMounts:
            - name: www
              mountPath: ${volMount:=/usr/share/nginx/html}
          params:
            paths: /usr/share/nginx/html
            exclude: /usr/share/nginx/html/tmp1
      retryConfig:
        maxRetry: 2
        delay: 1m
