apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo
  labels:
    app: nginx-app
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-app

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: demo
  # annotations:
  #   blueprint.kubestash.com/name: sts-blueprint
  #   blueprint.kubestash.com/namespace: default
  #   variables.kubestash.com/targetName: web
  #   variables.kubestash.com/namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-app # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
