apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: sample-retention
  namespace: demo
spec:
  default: true
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 5
  failedSnapshots:
    last: 2