apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      endpoint: us-east-1.linodeobjects.com
      bucket: kubestash
      region: us-east-1
      prefix: /stash-test
    storageSecretName: s3-secret
